[2025-05-03T14:14:05.631+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-05-03T14:14:05.652+0000] {taskinstance.py:2603} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: random_user_dag.send_request manual__2025-05-03T14:14:00.745739+00:00 [queued]>
[2025-05-03T14:14:05.663+0000] {taskinstance.py:2603} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: random_user_dag.send_request manual__2025-05-03T14:14:00.745739+00:00 [queued]>
[2025-05-03T14:14:05.663+0000] {taskinstance.py:2856} INFO - Starting attempt 1 of 1
[2025-05-03T14:14:05.682+0000] {taskinstance.py:2879} INFO - Executing <Task(PythonOperator): send_request> on 2025-05-03 14:14:00.745739+00:00
[2025-05-03T14:14:05.701+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=2158) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2025-05-03T14:14:05.707+0000] {standard_task_runner.py:72} INFO - Started process 2160 to run task
[2025-05-03T14:14:05.705+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'random_user_dag', 'send_request', 'manual__2025-05-03T14:14:00.745739+00:00', '--job-id', '14', '--raw', '--subdir', 'DAGS_FOLDER/air.py', '--cfg-path', '/tmp/tmpkedy7t_u']
[2025-05-03T14:14:05.714+0000] {standard_task_runner.py:105} INFO - Job 14: Subtask send_request
[2025-05-03T14:14:05.851+0000] {task_command.py:467} INFO - Running <TaskInstance: random_user_dag.send_request manual__2025-05-03T14:14:00.745739+00:00 [running]> on host d48b01d101a5
[2025-05-03T14:14:06.001+0000] {taskinstance.py:3122} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='random_user_dag' AIRFLOW_CTX_TASK_ID='send_request' AIRFLOW_CTX_EXECUTION_DATE='2025-05-03T14:14:00.745739+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-05-03T14:14:00.745739+00:00'
[2025-05-03T14:14:06.003+0000] {taskinstance.py:731} INFO - ::endgroup::
[2025-05-03T14:14:13.783+0000] {taskinstance.py:3301} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 406, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/utils.py", line 112, in pipeline
    write_s3()
  File "/opt/airflow/dags/utils.py", line 100, in write_s3
    wr.s3.to_csv(
  File "/home/airflow/.local/lib/python3.12/site-packages/awswrangler/_config.py", line 712, in wrapper
    return function(**args)
           ^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/awswrangler/_utils.py", line 179, in inner
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/awswrangler/s3/_write_text.py", line 590, in to_csv
    paths, partitions_values = _to_dataset(
                               ^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/awswrangler/s3/_write_dataset.py", line 254, in _to_dataset
    paths = func(
            ^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/awswrangler/_distributed.py", line 105, in wrapper
    return cls.dispatch_func(func)(*args, **kw)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/awswrangler/s3/_write_text.py", line 65, in _to_text
    with open_s3_object(
  File "/usr/local/lib/python3.12/contextlib.py", line 144, in __exit__
    next(self.gen)
  File "/home/airflow/.local/lib/python3.12/site-packages/awswrangler/s3/_fs.py", line 602, in open_s3_object
    text_s3obj.close()
  File "/home/airflow/.local/lib/python3.12/site-packages/awswrangler/s3/_fs.py", line 488, in close
    _utils.try_it(
  File "/home/airflow/.local/lib/python3.12/site-packages/awswrangler/_utils.py", line 790, in try_it
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/botocore/client.py", line 570, in _api_call
    return self._make_api_call(operation_name, kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/botocore/context.py", line 124, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/botocore/client.py", line 1031, in _make_api_call
    raise error_class(parsed_response, operation_name)
botocore.exceptions.ClientError: An error occurred (SignatureDoesNotMatch) when calling the PutObject operation: The request signature we calculated does not match the signature you provided. Check your key and signing method.
[2025-05-03T14:14:13.819+0000] {taskinstance.py:1225} INFO - Marking task as FAILED. dag_id=random_user_dag, task_id=send_request, run_id=manual__2025-05-03T14:14:00.745739+00:00, execution_date=20250503T141400, start_date=20250503T141405, end_date=20250503T141413
[2025-05-03T14:14:13.838+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2025-05-03T14:14:13.839+0000] {standard_task_runner.py:124} ERROR - Failed to execute job 14 for task send_request (An error occurred (SignatureDoesNotMatch) when calling the PutObject operation: The request signature we calculated does not match the signature you provided. Check your key and signing method.; 2160)
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py", line 117, in _start_by_fork
    ret = args.func(args, dag=self.dag)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/cli.py", line 115, in wrapper
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 483, in task_run
    task_return_code = _run_task_by_selected_method(args, _dag, ti)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 256, in _run_task_by_selected_method
    return _run_raw_task(args, ti)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 341, in _run_raw_task
    return ti._run_raw_task(
           ^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/session.py", line 97, in wrapper
    return func(*args, session=session, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 2995, in _run_raw_task
    return _run_raw_task(
           ^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 273, in _run_raw_task
    TaskInstance._execute_task_with_callbacks(
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3149, in _execute_task_with_callbacks
    result = self._execute_task(context, task_orig)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3173, in _execute_task
    return _execute_task(self, context, task_orig)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 406, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/utils.py", line 112, in pipeline
    write_s3()
  File "/opt/airflow/dags/utils.py", line 100, in write_s3
    wr.s3.to_csv(
  File "/home/airflow/.local/lib/python3.12/site-packages/awswrangler/_config.py", line 712, in wrapper
    return function(**args)
           ^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/awswrangler/_utils.py", line 179, in inner
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/awswrangler/s3/_write_text.py", line 590, in to_csv
    paths, partitions_values = _to_dataset(
                               ^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/awswrangler/s3/_write_dataset.py", line 254, in _to_dataset
    paths = func(
            ^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/awswrangler/_distributed.py", line 105, in wrapper
    return cls.dispatch_func(func)(*args, **kw)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/awswrangler/s3/_write_text.py", line 65, in _to_text
    with open_s3_object(
  File "/usr/local/lib/python3.12/contextlib.py", line 144, in __exit__
    next(self.gen)
  File "/home/airflow/.local/lib/python3.12/site-packages/awswrangler/s3/_fs.py", line 602, in open_s3_object
    text_s3obj.close()
  File "/home/airflow/.local/lib/python3.12/site-packages/awswrangler/s3/_fs.py", line 488, in close
    _utils.try_it(
  File "/home/airflow/.local/lib/python3.12/site-packages/awswrangler/_utils.py", line 790, in try_it
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/botocore/client.py", line 570, in _api_call
    return self._make_api_call(operation_name, kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/botocore/context.py", line 124, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/botocore/client.py", line 1031, in _make_api_call
    raise error_class(parsed_response, operation_name)
botocore.exceptions.ClientError: An error occurred (SignatureDoesNotMatch) when calling the PutObject operation: The request signature we calculated does not match the signature you provided. Check your key and signing method.
[2025-05-03T14:14:13.856+0000] {local_task_job_runner.py:261} INFO - Task exited with return code 1
[2025-05-03T14:14:13.875+0000] {taskinstance.py:3891} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-05-03T14:14:13.879+0000] {local_task_job_runner.py:240} INFO - ::endgroup::
